package model

const (
	// SeverityCritical indicates the finding is blocking and urgent.
	SeverityCritical = "critical"
	// SeverityHigh indicates the finding is important and should be addressed.
	SeverityHigh = "high"
	// SeverityMedium indicates the finding is moderately important.
	SeverityMedium = "medium"
	// SeverityLow indicates the finding is minor.
	SeverityLow = "low"
)

var validSeverities = []string{SeverityCritical, SeverityHigh, SeverityMedium, SeverityLow}

// ReviewSeverities returns the accepted LlmComment severity values.
func ReviewSeverities() []string {
	return append([]string(nil), validSeverities...)
}

const (
	CategoryBug             = "bug"
	CategorySecurity        = "security"
	CategoryPerformance     = "performance"
	CategoryMaintainability = "maintainability"
	CategoryTest            = "test"
	CategoryStyle           = "style"
	CategoryDocumentation   = "documentation"
	CategoryOther           = "other"
)

var validCategories = []string{
	CategoryBug,
	CategorySecurity,
	CategoryPerformance,
	CategoryMaintainability,
	CategoryTest,
	CategoryStyle,
	CategoryDocumentation,
	CategoryOther,
}

// ReviewCategories returns the accepted LlmComment category values.
func ReviewCategories() []string {
	return append([]string(nil), validCategories...)
}

// LlmComment represents a code review comment generated by the LLM.
type LlmComment struct {
	Path           string `json:"path"`
	Content        string `json:"content"`
	SuggestionCode string `json:"suggestion_code,omitempty"`
	ExistingCode   string `json:"existing_code,omitempty"`
	StartLine      int    `json:"start_line"`
	EndLine        int    `json:"end_line"`
	Thinking       string `json:"thinking,omitempty"`
	// Category classifies the finding. One of:
	// bug, security, performance, maintainability, test, style, documentation, other.
	Category string `json:"category,omitempty"`
	// Severity indicates the importance of the finding. One of:
	// critical, high, medium, low.
	Severity string `json:"severity,omitempty"`
}

// CodeReviewResult holds raw LLM-generated review suggestion for a code segment.
type CodeReviewResult struct {
	RelevantFile      string `json:"relevant_file"`
	SuggestionContent string `json:"suggestion_content"`
	ExistingCode      string `json:"existing_code"`
	SuggestionCode    string `json:"suggestion_code"`
}
